export type JustifyContent = 'start' | 'center' | 'end' | 'space-around' | 'space-between' | 'space-evenly';
export type AlignItems = 'start' | 'center' | 'end' | 'stretch' | 'space-between' | 'space-around' | 'baseline';

export type  LayoutAlign = JustifyContent
  | undefined
  | 'start start'
  | 'center  start'
  | 'end start'
  | 'space-around start'
  | 'space-between start'
  | 'space-evenly start'
  | 'start center'
  | 'center center'
  | 'end center'
  | 'space-around center'
  | 'space-between center'
  | 'space-evenly center'
  | 'start end'
  | 'center end'
  | 'end end'
  | 'space-around end'
  | 'space-between end'
  | 'space-evenly end'
  | 'start stretch'
  | 'center stretch'
  | 'end stretch'
  | 'space-around stretch'
  | 'space-between stretch'
  | 'space-evenly stretch'
  | 'start space-between'
  | 'center space-between'
  | 'end space-between'
  | 'space-around space-between'
  | 'space-between space-between'
  | 'space-evenly space-between'
  | 'start space-around'
  | 'center space-around'
  | 'end space-around'
  | 'space-around space-around'
  | 'space-between space-around'
  | 'space-evenly space-around'
  | 'start baseline'
  | 'center baseline'
  | 'end baseline'
  | 'space-around baseline'
  | 'space-between baseline'
  | 'space-evenly baseline'
  ;
