import {Directive, Input} from '@angular/core';
import {ThemeSizes} from 'cdk';

@Directive()
export abstract class AbstractIndentsDirective {
  @Input() airPadding: ThemeSizes;
  @Input('xs.airPadding') xsAirPadding: ThemeSizes;
  @Input('sm.airPadding') smAirPadding: ThemeSizes;
  @Input('md.airPadding') mdAirPadding: ThemeSizes;
  @Input('lg.airPadding') lgAirPadding: ThemeSizes;
  @Input('xl.airPadding') xlAirPadding: ThemeSizes;
  @Input('lt-sm.airPadding') ltSmAirPadding: ThemeSizes;
  @Input('lt-md.airPadding') ltMdAirPadding: ThemeSizes;
  @Input('lt-lg.airPadding') ltLgAirPadding: ThemeSizes;
  @Input('lt-xl.airPadding') ltXlAirPadding: ThemeSizes;
  @Input('gt-sm.airPadding') gtSmAirPadding: ThemeSizes;
  @Input('gt-md.airPadding') gtMdAirPadding: ThemeSizes;
  @Input('gt-lg.airPadding') gtLgAirPadding: ThemeSizes;
  @Input('gt-xs.airPadding') gtXsAirPadding: ThemeSizes;

  @Input() airPaddingTop: ThemeSizes;
  @Input('xs.airPaddingTop') xsAirPaddingTop: ThemeSizes;
  @Input('sm.airPaddingTop') smAirPaddingTop: ThemeSizes;
  @Input('md.airPaddingTop') mdAirPaddingTop: ThemeSizes;
  @Input('lg.airPaddingTop') lgAirPaddingTop: ThemeSizes;
  @Input('xl.airPaddingTop') xlAirPaddingTop: ThemeSizes;
  @Input('lt-sm.airPaddingTop') ltSmAirPaddingTop: ThemeSizes;
  @Input('lt-md.airPaddingTop') ltMdAirPaddingTop: ThemeSizes;
  @Input('lt-lg.airPaddingTop') ltLgAirPaddingTop: ThemeSizes;
  @Input('lt-xl.airPaddingTop') ltXlAirPaddingTop: ThemeSizes;
  @Input('gt-sm.airPaddingTop') gtSmAirPaddingTop: ThemeSizes;
  @Input('gt-md.airPaddingTop') gtMdAirPaddingTop: ThemeSizes;
  @Input('gt-lg.airPaddingTop') gtLgAirPaddingTop: ThemeSizes;
  @Input('gt-xs.airPaddingTop') gtXsAirPaddingTop: ThemeSizes;

  @Input() airPaddingBottom: ThemeSizes;
  @Input('xs.airPaddingBottom') xsAirPaddingBottom: ThemeSizes;
  @Input('sm.airPaddingBottom') smAirPaddingBottom: ThemeSizes;
  @Input('md.airPaddingBottom') mdAirPaddingBottom: ThemeSizes;
  @Input('lg.airPaddingBottom') lgAirPaddingBottom: ThemeSizes;
  @Input('xl.airPaddingBottom') xlAirPaddingBottom: ThemeSizes;
  @Input('lt-sm.airPaddingBottom') ltSmAirPaddingBottom: ThemeSizes;
  @Input('lt-md.airPaddingBottom') ltMdAirPaddingBottom: ThemeSizes;
  @Input('lt-lg.airPaddingBottom') ltLgAirPaddingBottom: ThemeSizes;
  @Input('lt-xl.airPaddingBottom') ltXlAirPaddingBottom: ThemeSizes;
  @Input('gt-sm.airPaddingBottom') gtSmAirPaddingBottom: ThemeSizes;
  @Input('gt-md.airPaddingBottom') gtMdAirPaddingBottom: ThemeSizes;
  @Input('gt-lg.airPaddingBottom') gtLgAirPaddingBottom: ThemeSizes;
  @Input('gt-xs.airPaddingBottom') gtXsAirPaddingBottom: ThemeSizes;

  @Input() airPaddingStart: ThemeSizes;
  @Input('xs.airPaddingStart') xsAirPaddingStart: ThemeSizes;
  @Input('sm.airPaddingStart') smAirPaddingStart: ThemeSizes;
  @Input('md.airPaddingStart') mdAirPaddingStart: ThemeSizes;
  @Input('lg.airPaddingStart') lgAirPaddingStart: ThemeSizes;
  @Input('xl.airPaddingStart') xlAirPaddingStart: ThemeSizes;
  @Input('lt-sm.airPaddingStart') ltSmAirPaddingStart: ThemeSizes;
  @Input('lt-md.airPaddingStart') ltMdAirPaddingStart: ThemeSizes;
  @Input('lt-lg.airPaddingStart') ltLgAirPaddingStart: ThemeSizes;
  @Input('lt-xl.airPaddingStart') ltXlAirPaddingStart: ThemeSizes;
  @Input('gt-sm.airPaddingStart') gtSmAirPaddingStart: ThemeSizes;
  @Input('gt-md.airPaddingStart') gtMdAirPaddingStart: ThemeSizes;
  @Input('gt-lg.airPaddingStart') gtLgAirPaddingStart: ThemeSizes;
  @Input('gt-xs.airPaddingStart') gtXsAirPaddingStart: ThemeSizes;

  @Input() airPaddingEnd: ThemeSizes;
  @Input('xs.airPaddingEnd') xsAirPaddingEnd: ThemeSizes;
  @Input('sm.airPaddingEnd') smAirPaddingEnd: ThemeSizes;
  @Input('md.airPaddingEnd') mdAirPaddingEnd: ThemeSizes;
  @Input('lg.airPaddingEnd') lgAirPaddingEnd: ThemeSizes;
  @Input('xl.airPaddingEnd') xlAirPaddingEnd: ThemeSizes;
  @Input('lt-sm.airPaddingEnd') ltSmAirPaddingEnd: ThemeSizes;
  @Input('lt-md.airPaddingEnd') ltMdAirPaddingEnd: ThemeSizes;
  @Input('lt-lg.airPaddingEnd') ltLgAirPaddingEnd: ThemeSizes;
  @Input('lt-xl.airPaddingEnd') ltXlAirPaddingEnd: ThemeSizes;
  @Input('gt-sm.airPaddingEnd') gtSmAirPaddingEnd: ThemeSizes;
  @Input('gt-md.airPaddingEnd') gtMdAirPaddingEnd: ThemeSizes;
  @Input('gt-lg.airPaddingEnd') gtLgAirPaddingEnd: ThemeSizes;
  @Input('gt-xs.airPaddingEnd') gtXsAirPaddingEnd: ThemeSizes;

  @Input() airMargin: ThemeSizes;
  @Input('xs.airMargin') xsAirMargin: ThemeSizes;
  @Input('sm.airMargin') smAirMargin: ThemeSizes;
  @Input('md.airMargin') mdAirMargin: ThemeSizes;
  @Input('lg.airMargin') lgAirMargin: ThemeSizes;
  @Input('xl.airMargin') xlAirMargin: ThemeSizes;
  @Input('lt-sm.airMargin') ltSmAirMargin: ThemeSizes;
  @Input('lt-md.airMargin') ltMdAirMargin: ThemeSizes;
  @Input('lt-lg.airMargin') ltLgAirMargin: ThemeSizes;
  @Input('lt-xl.airMargin') ltXlAirMargin: ThemeSizes;
  @Input('gt-sm.airMargin') gtSmAirMargin: ThemeSizes;
  @Input('gt-md.airMargin') gtMdAirMargin: ThemeSizes;
  @Input('gt-lg.airMargin') gtLgAirMargin: ThemeSizes;
  @Input('gt-xs.airMargin') gtXsAirMargin: ThemeSizes;

  @Input() airMarginTop: ThemeSizes;
  @Input('xs.airMarginTop') xsAirMarginTop: ThemeSizes;
  @Input('sm.airMarginTop') smAirMarginTop: ThemeSizes;
  @Input('md.airMarginTop') mdAirMarginTop: ThemeSizes;
  @Input('lg.airMarginTop') lgAirMarginTop: ThemeSizes;
  @Input('xl.airMarginTop') xlAirMarginTop: ThemeSizes;
  @Input('lt-sm.airMarginTop') ltSmAirMarginTop: ThemeSizes;
  @Input('lt-md.airMarginTop') ltMdAirMarginTop: ThemeSizes;
  @Input('lt-lg.airMarginTop') ltLgAirMarginTop: ThemeSizes;
  @Input('lt-xl.airMarginTop') ltXlAirMarginTop: ThemeSizes;
  @Input('gt-sm.airMarginTop') gtSmAirMarginTop: ThemeSizes;
  @Input('gt-md.airMarginTop') gtMdAirMarginTop: ThemeSizes;
  @Input('gt-lg.airMarginTop') gtLgAirMarginTop: ThemeSizes;
  @Input('gt-xs.airMarginTop') gtXsAirMarginTop: ThemeSizes;

  @Input() airMarginBottom: ThemeSizes;
  @Input('xs.airMarginBottom') xsAirMarginBottom: ThemeSizes;
  @Input('sm.airMarginBottom') smAirMarginBottom: ThemeSizes;
  @Input('md.airMarginBottom') mdAirMarginBottom: ThemeSizes;
  @Input('lg.airMarginBottom') lgAirMarginBottom: ThemeSizes;
  @Input('xl.airMarginBottom') xlAirMarginBottom: ThemeSizes;
  @Input('lt-sm.airMarginBottom') ltSmAirMarginBottom: ThemeSizes;
  @Input('lt-md.airMarginBottom') ltMdAirMarginBottom: ThemeSizes;
  @Input('lt-lg.airMarginBottom') ltLgAirMarginBottom: ThemeSizes;
  @Input('lt-xl.airMarginBottom') ltXlAirMarginBottom: ThemeSizes;
  @Input('gt-sm.airMarginBottom') gtSmAirMarginBottom: ThemeSizes;
  @Input('gt-md.airMarginBottom') gtMdAirMarginBottom: ThemeSizes;
  @Input('gt-lg.airMarginBottom') gtLgAirMarginBottom: ThemeSizes;
  @Input('gt-xs.airMarginBottom') gtXsAirMarginBottom: ThemeSizes;

  @Input() airMarginStart: ThemeSizes;
  @Input('xs.airMarginStart') xsAirMarginStart: ThemeSizes;
  @Input('sm.airMarginStart') smAirMarginStart: ThemeSizes;
  @Input('md.airMarginStart') mdAirMarginStart: ThemeSizes;
  @Input('lg.airMarginStart') lgAirMarginStart: ThemeSizes;
  @Input('xl.airMarginStart') xlAirMarginStart: ThemeSizes;
  @Input('lt-sm.airMarginStart') ltSmAirMarginStart: ThemeSizes;
  @Input('lt-md.airMarginStart') ltMdAirMarginStart: ThemeSizes;
  @Input('lt-lg.airMarginStart') ltLgAirMarginStart: ThemeSizes;
  @Input('lt-xl.airMarginStart') ltXlAirMarginStart: ThemeSizes;
  @Input('gt-sm.airMarginStart') gtSmAirMarginStart: ThemeSizes;
  @Input('gt-md.airMarginStart') gtMdAirMarginStart: ThemeSizes;
  @Input('gt-lg.airMarginStart') gtLgAirMarginStart: ThemeSizes;
  @Input('gt-xs.airMarginStart') gtXsAirMarginStart: ThemeSizes;

  @Input() airMarginEnd: ThemeSizes;
  @Input('xs.airMarginEnd') xsAirMarginEnd: ThemeSizes;
  @Input('sm.airMarginEnd') smAirMarginEnd: ThemeSizes;
  @Input('md.airMarginEnd') mdAirMarginEnd: ThemeSizes;
  @Input('lg.airMarginEnd') lgAirMarginEnd: ThemeSizes;
  @Input('xl.airMarginEnd') xlAirMarginEnd: ThemeSizes;
  @Input('lt-sm.airMarginEnd') ltSmAirMarginEnd: ThemeSizes;
  @Input('lt-md.airMarginEnd') ltMdAirMarginEnd: ThemeSizes;
  @Input('lt-lg.airMarginEnd') ltLgAirMarginEnd: ThemeSizes;
  @Input('lt-xl.airMarginEnd') ltXlAirMarginEnd: ThemeSizes;
  @Input('gt-sm.airMarginEnd') gtSmAirMarginEnd: ThemeSizes;
  @Input('gt-md.airMarginEnd') gtMdAirMarginEnd: ThemeSizes;
  @Input('gt-lg.airMarginEnd') gtLgAirMarginEnd: ThemeSizes;
  @Input('gt-xs.airMarginEnd') gtXsAirMarginEnd: ThemeSizes;
}
