export {clone} from './clone';
export {htmlToText, isHtmlString, isPureText} from './html-to-text';
export {getValuesFromSimpleChanges} from './get-values-from-simple-changes';
export {mapObjectKeys} from './map-object-keys';
export {randomId} from './random-id';
export {toNumber} from './type-transformers';
export {url} from './url';
export * from './string';
export * from './forms';
export {throwIf} from './throw-if';
export * from './diff';
export {fillObject} from './fill-object';
export {patch, cloneAndPatch} from './patch';
export {portalContainerId} from './portal-container-id';
export {concatUnique} from './concat-unique';
export {observeResize} from './observe-resize';
export * from './clone-deep-and-merge';
export * from './map-to-object';
